#!/usr/bin/env bash

#############################################################################################
##                    KUBECI RUNNER
#############################################################################################
set -e

#############################################################################################
##                    import
#############################################################################################
. ${KUBECI_PATH}/shell-utils/screen-utils.sh
. ${KUBECI_PATH}/shell-utils/version-utils.sh

#############################################################################################
##                    variables
#############################################################################################
help=0;
d=0;
bs=0;
bd=0;
all=0
export global_projectsToBuild=""
version=$(VersionUtils.readVersion)
ScreenUtils.echoImportant "Running version ${version}"

#############################################################################################
##                    options
#############################################################################################
for i in "$@"
do
case $i in

    -s=*|--sourceFolder=*)
        export SOURCE_FOLDER="${i#*=}"
        echo "SOURCE_FOLDER $SOURCE_FOLDER"
    ;;
    -p=*|--projectId=*)
        export PROJECT_ID="${i#*=}"
       echo "PROJECT_ID $BUILD_INCREMENT"
    ;;
    -bi=*|--buildIncrement=*)
       export BUILD_INCREMENT="${i#*=}"
       echo "BUILD_INCREMENT $BUILD_INCREMENT"
    ;;
    -h|--help)
     read -r -d '' help << EOM
    Available options are:
    -p (--projectId) GOOGLE CLOUD PROJECT ID
    -s (--sourceFolder) SOURCE FOLDER
    -bi (--buildIncrement) BUILD INCREMENT
    -bs (--buildSource) To build source of your application
    -bd (--buildDocker) To build docker of your application
    -d (--deploy) To deploy your application
EOM
    echo "${help}"
    ;;
    -a|--all)
        all=1
    ;;
    -bs|--buildSource)
        bs=1
    ;;
    -bd|--buildDocker)
       bd=1
    ;;
    -d|--deploy)
        d=1
    ;;
esac
done

verifySourceParameter(){
    if [ -z ${SOURCE_FOLDER} ]
    then
        ScreenUtils.echoError "SOURCE_FOLDER parameter is missing"
    fi
}

#############################################################################################
##                    Initialize
#############################################################################################
. ${KUBECI_PATH}/init/init.sh $all
cd ${SOURCE_FOLDER}


#############################################################################################
##                    Build sources
#############################################################################################
if [ ${bs} -eq 1 ]
then
   verifySourceParameter
   echo "BUILD SOURCE"
    cd ${SOURCE_FOLDER}
   . ${KUBECI_PATH}/build/sources.sh
fi


#############################################################################################
##                    Build Docker
#############################################################################################
if [ ${bd} -eq 1 ]
then
    verifySourceParameter
    echo "BUILD DOCKER"
    cd ${SOURCE_FOLDER}
    . ${KUBECI_PATH}/docker/docker.sh
fi

#############################################################################################
##                    Deploy
#############################################################################################
if [ ${d} -eq 1 ]
then
    verifySourceParameter
    if [ -z ${DNS} ]
    then
        echo "DNS Name is empty for current branch, please verify your .deployments.gitlab-ci.yml file"
    else
        echo "DEPLOY"
        cd ${SOURCE_FOLDER}
        . ${KUBECI_PATH}/helm/helm-apply.sh
        . ${KUBECI_PATH}/kubernetes/kubectl-apply.sh
    fi
fi

