apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{.Values.NAMESPACE}}
  name: web-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      name: web-server-pod
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: gcr.io/{{.Values.PROJECT_ID}}/web-server:{{.Values.VERSION}}